### PR TITLE
2.12ification #74

### PR DESCRIPTION
**Pull request by idarlington**
**Problem** 

Project needs to support  scala 2.12 and tested to make sure it compiles.

**Solution**

Added crossScalaVersions to the build.scala file

**Result**
Project now supports Scala 2.12 and compiles

### CODE REVIEW

**Comment by mosesn** [comment]
@idarlington how did you compile it / run tests?  I have to say, I'm pretty surprised this works.  Did you try `./sbt +test`?

**Comment by idarlington** [comment]
Running crossversion test shows this : 

```
[info] Tests: succeeded 102, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	com.twitter.ostrich.admin.config.ServerConfigSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
```

**Comment by mosesn** [comment]
Oh, I see!  OK, we probably want to figure out why that test failed and fix it before we merge this in.  Also, can you update the [.travis.yml][0] file to add 2.12.0-M4?

Did you see our discussion on the other ticket about whether it might be possible to move from scala-json to jackson?  Would you be interested in tackling that?

[0]: https://github.com/twitter/ostrich/blob/develop/.travis.yml

**Comment by idarlington** [comment]
Hi @mosesn , this is the error :
```
[info] - configure Logger with loggerConfig when LoggerFactories not specified *** FAILED ***
[info]   Handler;(<com.twitter.logging.ScribeHandler level=ALL hostname=localhost port=1463 scribe_buffer=100.milliseconds scribe_backoff=15.seconds scribe_max_packet_size=1000 formatter=com.twitter.logging.Formatter@511d438f>) had size 1 instead of expected size 0 (ServerConfigSpec.scala:62)
```

Any ideas on why the test fails?

**Comment by mosesn** [comment]
Someone is moving ostrich off of scala-json now, so we'll be able to merge this in soon!  Very excited =)

**Comment by mosesn** [comment]
re: .travis.yml, let's just sit tight for now, but make sure all of the tests pass.  I don't know why that test fails, but it looks like it's in util, not in ostrich, right?  So it should be OK.  Might be worth filing a ticket on util?

**Comment by mosesn** [comment]
https://github.com/twitter/ostrich/commit/80fe2dd4173b171f0d0e21b0a67671ca1e019447 landed, so this might be ready for the big time.  Thanks for your patience @idarlington!

**Comment by bryce-anderson** [comment]
We are waiting for the imminent [2.8.1 release](https://github.com/FasterXML/jackson-module-scala/issues/270) of `jackson-module-scala`, which should have a scala `2.12.0-M4` build, and then we will get this merged. Thanks for your patience @idarlington!

**Comment by vkostyukov** [comment]
Thanks @idarlington! I'm pulling this internally. Will close this ticket once it's merged.

**Comment by mosesn** [comment]
@idarlington sorry for the long silence, this ended up requiring more internal work than we thought it needed.  we're still working on it!

**Comment by idarlington** [comment]
Hi, @mosesn , I am fine with that. What other projects have issues I can work on ?

**Comment by mosesn** [comment]
[Finagle][0] and [Scrooge][1] both have lots of starter tickets!

[0]: https://github.com/twitter/finagle/issues?q=is%3Aopen+is%3Aissue+label%3AStarter
[1]: https://github.com/twitter/scrooge/issues?q=is%3Aopen+is%3Aissue+label%3AStarter

**Comment by mosesn** [comment]
@idarlington this was finally merged internally.  thanks for your patience!

**Comment by ryanoneill** [comment]
Hi @idarlington, thank you for your contribution. This has been pushed back out to GitHub in https://github.com/twitter/ostrich/commit/1a819b1fb76740fd81348c6e484fe5abed69ffe7

Now going to close this pull request.

**Pull request closed without merging**
