### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### GitHub Corrected URLs 
Was | Now 
--- | --- 
https://github.com/mariusaeriksen/heapster | https://github.com/mariusae/heapster

### CODE REVIEW

**Comment by kevinoliver** [comment]
Thanks @ReadmeCritic. We'll get this merged in.

**Comment by kevinoliver** [comment]
Ok, merged this internally and it'll get pushed back out to the `develop` branch this coming Monday. Thanks again.

**Comment by ReadmeCritic** [comment]
ok

**Comment by mosesn** [comment]
Merged internally!  https://github.com/twitter/ostrich/commit/88f122a9f29b0d644d6412e9ff1b8ecc9bfbc30e

Thanks =)

**Pull request closed without merging**
